### ISSUE TITLE
Goofy header behavior

### ISSUE THREAD

**Issue by lino-levan** [denoland/dotland#2591]
If you click on a section on the header, it will keep that section open even if the user's mouse leaves the hover area. This results in some goofy looking behavior in specific circumstances.

Reproc steps:
1. Click "Modules" text
2. Hover over "Docs"

Fix:
- Either remove on-click behavior or disable on-hover behavior after the user has clicked on another nav element

<img width="1440" alt="Screenshot 2022-11-15 at 2 43 59 PM" src="https://user-images.githubusercontent.com/11367844/202040560-8f7728af-ff83-4034-b6c1-f452771ad257.png">

**Comment by WittySmirk** [comment]
We can't disable onclick behavior because it is essential for mobile. 

Not quite sure how to disable on hover for the other nav elements once one is clicked because each nav element is seperated by 2 layers (you would have to disable the hover css for the parent of the parent's children).

I tried to do this but it doesnt seem to work
```js
<input
     type="checkbox"
     id={entry.content}
     class="hidden checked:(siblings:last-child:block sibling:children:last-child:children:(odd:hidden even:block) parent:parent:children:hover:children(hidden))"
     autoComplete="off"
 />
```
