### ISSUE TITLE
Confusion about Sub Process Manual section.

### ISSUE THREAD

**Issue by nhrones** [denoland/dotland#2734]
In the Sub Process section of the manual, The new Deno.Command, and Deno.Run sections are combined in this section.  I have been told that run is to be deprecated.  Should that not be in the documentation?  Also, there is no indication if any of these types/classes are unstable?  Should I assume if not documented, that all are stable?

**Comment by GJZwiers** [comment]
AFAIK the deprecation of Deno.run was reverted to allow users more time to switch to the newer Deno.Command API. See https://github.com/denoland/deno/pull/17875. Since Deno.Command is now stable, Deno.run might be deprecated in the near future.

The docs are outdated on this topic but there is an issue about it in the manual repo: https://github.com/denoland/manual/issues/597. If you want to know if an API is stable/unstable you can also check the API docs at https://deno.land/api.
