### ISSUE TITLE
Port website to deno

### ISSUE THREAD

**Issue by trivikr** [denoland/dotland#491]
The README states that

> This is written in React / TailwindCSS / Vercel / CloudFlare Workers. Not in Deno. Ideally this could be ported to Deno at some point but we are in need of a new website and dogfooding takes too long. We hope to see this code ported to Deno with minimal developer flow interrupted (in particular, we need the ability to listen for FS events and reload the web server).

As Deno has now released 1.0, can the work to move website to deno get prioritized?

The Node.js community loves that this website runs on node, but it's an easy laughing stock for questioning capabilities of Deno (check replies to [example tweet](https://twitter.com/matteocollina/status/1261254765348032512?s=09))

**Comment by mcollina** [comment]
As the author of that tweet, there is nothing mocking in it from my side. I genuinely love it, as Next.js is a fantastic framework.

(As much as it would if it was running on Wordpress - which is still fantastic).

**Comment by lucacasonato** [comment]
I fully agree that this will be great to do. The website can be ported when Deno is ready for this. Currently the tooling that is needed to make a good, high performance site like tree shaking and code splitting capable bundlers, static generation frameworks, css bundlers, minifiers ect are just not there yet.

Next.js is a really great framework, but sadly only exists for node. Having the Deno team develop an entire tooling stack simmilar in capability to Next.js to support the Deno website being written in Deno seems unreasonable. The people that are building the Deno runtime should build the Deno runtime and not web frameworks. With some more time the community will hopefully build and port enough tooling to Deno so that the website can be ported to Deno. :rocket:

I think the top priority should be the runtime and not the website though :-)

**Comment by joehua87** [comment]
I can port this website to run on Deno runtime with SSR & minimal code changed

The dev tool is still rely on some Node lib (rollup, react) for better DX

The idea is leverage ESM & reuse between Client Side & Server Side

Let me know if you will accept a PR @lucacasonato

**Comment by ry** [comment]
Let's wait a bit longer.

I really want to dog food deno here too - but not yet. The website is working today - I don't have to put much time into it - I would like it to remain that way so I can focus on problems deeper inside deno.

**Comment by ry** [comment]
My position has changed. We now want to port this website to Deno.

I will leave undefined how exactly this should be done, what tooling should be used. However here are some candidates:
- https://github.com/lucacasonato/dext.ts
- https://packup.deno.dev/
- https://github.com/lucacasonato/fresh

**Comment by yordis** [comment]
@ry any opinions on https://github.com/alephjs/aleph.js ? Just curious about the ecosystem in general, NextJS is the only thing keeping me in NodeJS for my web servers so I am eager from your decisions.

**Comment by ry** [comment]
This is being done in #2017
