### ISSUE TITLE
Visual Styling & Code Re-use

### ISSUE THREAD

**Issue by buckle2000** [denoland/dotland#660]
1. There are many `outline-none` in the source code. It is really a bad idea to override the default `:focus` link style, so please remove those.
2. The class names are too verbose. I found this link:
https://tailwindcss.com/docs/utility-first#maintainability-concerns

I'd like to fixed them myself, by the project development server takes too much memory. #556

**Comment by lucacasonato** [comment]
> 1. There are many outline-none in the source code. It is really a bad idea to override the default :focus link style, so please remove those.

In all cases where `outline-none` is used a sufficiently contrasting background color is applied on focus AFAIK. That should remove the need for an outline from an accessibility standpoint as far as I know. If I am missing something here please let me know.

> 2. The class names are too verbose. I found this link:
https://tailwindcss.com/docs/utility-first#maintainability-concerns

It can make sense to extract some utilities into classes, but in many cases the styling is very specific to a certain context, so it makes more sense not to extract them into components, because they are not actually reused. If there are specific cases where you think it makes sense, please list them.

**Comment by buckle2000** [comment]
1. I think the "Runtime API" in the header of https://deno.land/ doesn't have enough contrast.

2. For example:
Inconsistency (I think they are supposed to look the same):
https://github.com/denoland/deno_website2/blob/f6a0a65c8f1baea1e17d1f24994e5167f638940e/components/Header.tsx#L52
https://github.com/denoland/deno_website2/blob/f6a0a65c8f1baea1e17d1f24994e5167f638940e/components/Header.tsx#L57
https://github.com/denoland/deno_website2/blob/f6a0a65c8f1baea1e17d1f24994e5167f638940e/components/Footer.tsx#L14

Repetition:
https://github.com/denoland/deno_website2/blob/f6a0a65c8f1baea1e17d1f24994e5167f638940e/components/Manual.tsx#L487-L497
https://github.com/denoland/deno_website2/blob/f6a0a65c8f1baea1e17d1f24994e5167f638940e/components/Manual.tsx#L506-L518

**Comment by lucacasonato** [comment]
> 1.

You're right. I don't know why 'Runtime API' is different to the rest.

I'll look into these. These are good candidates for extraction :+1: 

> 2.

That gets repeated twice, is it worth it at that point?

**Comment by buckle2000** [comment]
All the repetition adds up quickly when reading code. It makes me tired faster.

**Comment by kingdaro** [comment]
IMO, as a middle ground, it's only worth abstraction if it's either repeated more than twice, or the repeated places are changed multiple times (indicating they should be the same thing)

**Comment by crowlKats** [comment]
Closing as doesnt apply anymore
